/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/health": {
		/**
		 * Health Check
		 * @description Check the health status of the API service
		 */
		get: operations["healthCheck"];
	};
	"/api/v1/items": {
		/**
		 * List Items
		 * @description Retrieve a paginated list of items in a project
		 */
		get: operations["listItems"];
	};
	"/api/v1/items/{item_id}": {
		/**
		 * Get Item
		 * @description Retrieve detailed information about a specific item
		 */
		get: operations["getItem"];
	};
	"/api/v1/links": {
		/**
		 * List Links
		 * @description Retrieve a paginated list of links between items in a project
		 */
		get: operations["listLinks"];
	};
	"/api/v1/analysis/impact/{item_id}": {
		/**
		 * Impact Analysis
		 * @description Analyze the impact of changes to a specific item, including all downstream dependencies
		 */
		get: operations["getImpactAnalysis"];
	};
	"/api/v1/analysis/cycles/{project_id}": {
		/**
		 * Detect Cycles
		 * @description Detect circular dependencies in the project's dependency graph
		 */
		get: operations["detectCycles"];
	};
	"/api/v1/analysis/shortest-path": {
		/**
		 * Find Shortest Path
		 * @description Find the shortest dependency path between two items
		 */
		get: operations["findShortestPath"];
	};
	"/api/v1/projects/{projectId}/equivalences": {
		/**
		 * List Equivalences
		 * @description Retrieve all equivalence relationships in a project
		 */
		get: operations["listEquivalences"];
	};
	"/api/v1/projects/{projectId}/equivalences/detect": {
		/**
		 * Detect Equivalences
		 * @description Automatically detect potential equivalent items across different views and dimensions
		 */
		post: operations["detectEquivalences"];
	};
	"/api/v1/equivalences/{id}/confirm": {
		/**
		 * Confirm Equivalence
		 * @description Confirm a suggested equivalence relationship between items
		 */
		post: operations["confirmEquivalence"];
	};
	"/api/v1/equivalences/{id}/reject": {
		/**
		 * Reject Equivalence
		 * @description Reject a suggested equivalence relationship between items
		 */
		post: operations["rejectEquivalence"];
	};
	"/api/v1/projects/{projectId}/canonical-concepts": {
		/**
		 * List Canonical Concepts
		 * @description Retrieve all canonical concepts in a project
		 */
		get: operations["listCanonicalConcepts"];
		/**
		 * Create Canonical Concept
		 * @description Create a new canonical concept from equivalent items
		 */
		post: operations["createCanonicalConcept"];
	};
	"/api/v1/canonical-concepts/{id}": {
		/**
		 * Get Canonical Concept
		 * @description Retrieve detailed information about a specific canonical concept
		 */
		get: operations["getCanonicalConcept"];
	};
	"/api/v1/canonical-concepts/{id}/projections": {
		/**
		 * Get Concept Projections
		 * @description Retrieve all projections of a canonical concept across different dimensions
		 */
		get: operations["getConceptProjections"];
	};
	"/api/v1/items/{id}/pivot": {
		/**
		 * Pivot Item to Canonical Concept
		 * @description Convert an item to a canonical concept projection, updating cross-dimensional references
		 */
		post: operations["pivotItemToCanonical"];
	};
	"/api/v1/projects/{projectId}/journeys": {
		/**
		 * List Journeys
		 * @description Retrieve all journeys in a project
		 */
		get: operations["listJourneys"];
		/**
		 * Create Journey
		 * @description Create a new journey mapping requirements through a process
		 */
		post: operations["createJourney"];
	};
	"/api/v1/projects/{projectId}/journeys/detect": {
		/**
		 * Detect Journeys
		 * @description Automatically detect potential journeys from requirement traces
		 */
		post: operations["detectJourneys"];
	};
	"/api/v1/journeys/{id}": {
		/**
		 * Get Journey
		 * @description Retrieve detailed information about a specific journey
		 */
		get: operations["getJourney"];
	};
	"/api/v1/projects/{projectId}/component-libraries": {
		/**
		 * List Component Libraries
		 * @description Retrieve all component libraries in a project
		 */
		get: operations["listComponentLibraries"];
	};
	"/api/v1/component-libraries/{id}/components": {
		/**
		 * List Components in Library
		 * @description Retrieve all components in a specific library
		 */
		get: operations["listLibraryComponents"];
	};
	"/api/v1/components/{id}/usage": {
		/**
		 * Get Component Usage
		 * @description Retrieve usage information for a specific component
		 */
		get: operations["getComponentUsage"];
	};
	"/api/v1/component-libraries/{id}/tokens": {
		/**
		 * Get Design Tokens
		 * @description Retrieve design tokens for a component library
		 */
		get: operations["getDesignTokens"];
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {
		HealthResponse: {
			/**
			 * @description Current health status of the service
			 * @enum {string}
			 */
			status: "healthy" | "degraded" | "unhealthy";
			/** @description API version */
			version: string;
			/** @description Service name */
			service: string;
		};
		ItemSummary: {
			/**
			 * Format: uuid
			 * @description Unique identifier for the item
			 */
			id: string;
			/** @description Item title */
			title: string;
			/** @description View type of the item */
			view: string;
			/**
			 * @description Current status of the item
			 * @enum {string}
			 */
			status: "draft" | "in_progress" | "completed" | "approved" | "rejected";
		};
		ItemListResponse: {
			/** @description Total number of items */
			total: number;
			items: components["schemas"]["ItemSummary"][];
		};
		ItemDetailResponse: {
			/** Format: uuid */
			id: string;
			title: string;
			description?: string | null;
			view: string;
			status: string;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at: string;
		};
		LinkSummary: {
			/** Format: uuid */
			id: string;
			/**
			 * Format: uuid
			 * @description Source item ID
			 */
			source_id: string;
			/**
			 * Format: uuid
			 * @description Target item ID
			 */
			target_id: string;
			/**
			 * @description Type of relationship
			 * @enum {string}
			 */
			type: "depends_on" | "implements" | "tests" | "derives_from";
		};
		LinkListResponse: {
			total: number;
			links: components["schemas"]["LinkSummary"][];
		};
		ImpactAnalysisResponse: {
			/**
			 * Format: uuid
			 * @description ID of the item being analyzed
			 */
			root_item_id: string;
			/** @description Total number of items affected by changes */
			total_affected: number;
			/** @description Maximum depth of dependency chain */
			max_depth: number;
			/** @description List of affected item IDs */
			affected_items: string[];
		};
		CycleDetectionResponse: {
			/** @description Whether cycles were detected */
			has_cycles: boolean;
			/** @description Number of cycles found */
			total_cycles: number;
			/**
			 * @description Severity level of detected cycles
			 * @enum {string}
			 */
			severity: "none" | "low" | "medium" | "high" | "critical";
			/** @description Items involved in cycles */
			affected_items: string[];
		};
		ShortestPathResponse: {
			/** @description Whether a path exists between the items */
			exists: boolean;
			/** @description Number of hops in the shortest path */
			distance: number | null;
			/** @description Ordered list of item IDs in the path */
			path: string[];
			/** @description Types of links in the path */
			link_types: string[];
		};
		EquivalenceResponse: {
			/**
			 * Format: uuid
			 * @description Unique identifier for the equivalence
			 */
			id: string;
			/** @description IDs of equivalent items */
			item_ids: string[];
			/**
			 * @description Current status of the equivalence
			 * @enum {string}
			 */
			status: "suggested" | "confirmed" | "rejected";
			/** @description Confidence score for the equivalence (0-1) */
			confidence: number;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at?: string;
			/** @description Optional notes about the equivalence */
			notes?: string | null;
		};
		EquivalenceListResponse: {
			total: number;
			equivalences: components["schemas"]["EquivalenceResponse"][];
		};
		DetectEquivalencesRequest: {
			/** @description List of dimensions to check for equivalences */
			dimensions: string[];
			/**
			 * @description Similarity threshold for automatic detection
			 * @default 0.8
			 */
			threshold?: number;
			/** @description Item IDs to exclude from detection */
			exclude_ids?: string[];
		};
		EquivalenceDetectionResponse: {
			/** @description Number of equivalences detected */
			detected_count: number;
			/** @description List of suggested equivalences */
			suggestions: components["schemas"]["EquivalenceResponse"][];
		};
		ConfirmEquivalenceRequest: {
			/** @description Optional notes when confirming */
			notes?: string;
		};
		RejectEquivalenceRequest: {
			/** @description Reason for rejecting the equivalence */
			reason?: string;
		};
		CanonicalConceptResponse: {
			/**
			 * Format: uuid
			 * @description Unique identifier for the canonical concept
			 */
			id: string;
			/** @description Name of the canonical concept */
			name: string;
			/** @description Detailed description */
			description: string | null;
			/** @description IDs of items that project this concept */
			item_ids: string[];
			/** @description Dimensions covered by this concept */
			dimensions?: string[];
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at?: string;
		};
		CanonicalConceptListResponse: {
			total: number;
			concepts: components["schemas"]["CanonicalConceptResponse"][];
		};
		CreateCanonicalConceptRequest: {
			/** @description Name of the canonical concept */
			name: string;
			/** @description Optional description */
			description?: string;
			/** @description IDs of items to include in this concept */
			item_ids: string[];
		};
		ProjectionResponse: {
			/** Format: uuid */
			id: string;
			/**
			 * Format: uuid
			 * @description ID of the projected item
			 */
			item_id: string;
			/** @description Dimension of this projection */
			dimension: string;
			/**
			 * Format: uuid
			 * @description ID of the canonical concept
			 */
			canonical_id: string;
			mapping_confidence?: number;
		};
		ProjectionListResponse: {
			total: number;
			projections: components["schemas"]["ProjectionResponse"][];
		};
		PivotItemRequest: {
			/**
			 * Format: uuid
			 * @description ID of the canonical concept to pivot to
			 */
			canonical_concept_id: string;
			/**
			 * @description Whether to update all references to this item
			 * @default true
			 */
			update_references?: boolean;
		};
		PivotItemResponse: {
			/** Format: uuid */
			item_id: string;
			/** Format: uuid */
			canonical_concept_id: string;
			/** @description Number of references updated */
			updated_references: number;
		};
		JourneyResponse: {
			/**
			 * Format: uuid
			 * @description Unique identifier for the journey
			 */
			id: string;
			/** @description Name of the journey */
			name: string;
			/** @description Detailed description */
			description?: string | null;
			/**
			 * @description Type of journey
			 * @enum {string}
			 */
			type: "user" | "system" | "data" | "integration";
			/** @description Ordered steps in the journey */
			steps: components["schemas"]["JourneyStep"][];
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at?: string;
		};
		JourneyStep: {
			/** Format: uuid */
			id: string;
			/** @description Position in the journey sequence */
			order: number;
			/** @description Name of this step */
			name: string;
			/**
			 * Format: uuid
			 * @description Associated requirement item ID
			 */
			item_id: string;
			description?: string | null;
			/** @description Additional step metadata */
			metadata?: Record<string, never>;
		};
		JourneyListResponse: {
			total: number;
			journeys: components["schemas"]["JourneyResponse"][];
		};
		CreateJourneyRequest: {
			/** @description Name of the journey */
			name: string;
			/** @description Optional description */
			description?: string;
			/**
			 * @description Type of journey
			 * @enum {string}
			 */
			type: "user" | "system" | "data" | "integration";
			steps: {
				order: number;
				name: string;
				/** Format: uuid */
				item_id: string;
				description?: string;
			}[];
		};
		DetectJourneysRequest: {
			/**
			 * @description Type of journey to detect
			 * @enum {string}
			 */
			journey_type: "user" | "system" | "data" | "integration";
			/**
			 * @description Minimum number of steps for a valid journey
			 * @default 3
			 */
			min_path_length?: number;
			/** @default 100 */
			max_results?: number;
		};
		JourneyDetectionResponse: {
			/** @description Number of journeys detected */
			detected_count: number;
			/** @description List of detected journeys */
			journeys: components["schemas"]["JourneyResponse"][];
		};
		ComponentLibraryResponse: {
			/**
			 * Format: uuid
			 * @description Unique identifier for the library
			 */
			id: string;
			/** @description Name of the component library */
			name: string;
			description?: string | null;
			/** @description Semantic version of the library */
			version: string;
			/** @description Number of components in the library */
			component_count?: number;
			/** Format: date-time */
			created_at: string;
			/** Format: date-time */
			updated_at?: string;
		};
		ComponentLibraryListResponse: {
			total: number;
			libraries: components["schemas"]["ComponentLibraryResponse"][];
		};
		ComponentResponse: {
			/** Format: uuid */
			id: string;
			/** @description Component name */
			name: string;
			description?: string | null;
			/** @description Component category */
			category: string;
			/** Format: uuid */
			library_id: string;
			/**
			 * @description Component status
			 * @enum {string}
			 */
			status?: "draft" | "published" | "deprecated";
			/** @description Component-specific properties */
			properties?: Record<string, never>;
		};
		ComponentListResponse: {
			total: number;
			components: components["schemas"]["ComponentResponse"][];
		};
		ComponentUsageResponse: {
			/** Format: uuid */
			component_id: string;
			/** @description Total number of usages */
			usage_count: number;
			/** @description IDs of items using this component */
			used_in_items: string[];
			/**
			 * Format: date-time
			 * @description When the component was last used
			 */
			last_used?: string | null;
		};
		DesignToken: {
			/** Format: uuid */
			id: string;
			/** @description Token name */
			name: string;
			/** @description Token value */
			value: string;
			/**
			 * @description Token category
			 * @enum {string}
			 */
			category:
				| "colors"
				| "typography"
				| "spacing"
				| "shadows"
				| "borders"
				| "other";
			description?: string | null;
		};
		DesignTokenResponse: {
			/** Format: uuid */
			library_id: string;
			tokens: components["schemas"]["DesignToken"][];
			total?: number;
		};
		Error: {
			/** @description Error message */
			detail: string;
			/** @description Error code for programmatic handling */
			code?: string;
		};
	};
	responses: {
		/** @description Bad Request - Invalid input parameters */
		BadRequest: {
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description Unauthorized - Missing or invalid authentication */
		Unauthorized: {
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description Not Found - Resource does not exist */
		NotFound: {
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
		/** @description Internal Server Error */
		InternalServerError: {
			content: {
				"application/json": components["schemas"]["Error"];
			};
		};
	};
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
	/**
	 * Health Check
	 * @description Check the health status of the API service
	 */
	healthCheck: {
		responses: {
			/** @description Service is healthy */
			200: {
				content: {
					"application/json": components["schemas"]["HealthResponse"];
				};
			};
		};
	};
	/**
	 * List Items
	 * @description Retrieve a paginated list of items in a project
	 */
	listItems: {
		parameters: {
			query: {
				/** @description Unique identifier for the project */
				project_id: string;
				/** @description Number of items to skip (for pagination) */
				skip?: number;
				/** @description Maximum number of items to return */
				limit?: number;
			};
		};
		responses: {
			/** @description Successfully retrieved items */
			200: {
				content: {
					"application/json": components["schemas"]["ItemListResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			500: components["responses"]["InternalServerError"];
		};
	};
	/**
	 * Get Item
	 * @description Retrieve detailed information about a specific item
	 */
	getItem: {
		parameters: {
			path: {
				/** @description Unique identifier for the item */
				item_id: string;
			};
		};
		responses: {
			/** @description Successfully retrieved item */
			200: {
				content: {
					"application/json": components["schemas"]["ItemDetailResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * List Links
	 * @description Retrieve a paginated list of links between items in a project
	 */
	listLinks: {
		parameters: {
			query: {
				/** @description Unique identifier for the project */
				project_id: string;
				skip?: number;
				limit?: number;
			};
		};
		responses: {
			/** @description Successfully retrieved links */
			200: {
				content: {
					"application/json": components["schemas"]["LinkListResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
		};
	};
	/**
	 * Impact Analysis
	 * @description Analyze the impact of changes to a specific item, including all downstream dependencies
	 */
	getImpactAnalysis: {
		parameters: {
			query: {
				/** @description Unique identifier for the project */
				project_id: string;
			};
			path: {
				/** @description Unique identifier for the item to analyze */
				item_id: string;
			};
		};
		responses: {
			/** @description Impact analysis completed successfully */
			200: {
				content: {
					"application/json": components["schemas"]["ImpactAnalysisResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Detect Cycles
	 * @description Detect circular dependencies in the project's dependency graph
	 */
	detectCycles: {
		parameters: {
			path: {
				/** @description Unique identifier for the project */
				project_id: string;
			};
		};
		responses: {
			/** @description Cycle detection completed successfully */
			200: {
				content: {
					"application/json": components["schemas"]["CycleDetectionResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Find Shortest Path
	 * @description Find the shortest dependency path between two items
	 */
	findShortestPath: {
		parameters: {
			query: {
				/** @description Unique identifier for the project */
				project_id: string;
				/** @description Starting item ID */
				source_id: string;
				/** @description Target item ID */
				target_id: string;
			};
		};
		responses: {
			/** @description Path search completed successfully */
			200: {
				content: {
					"application/json": components["schemas"]["ShortestPathResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * List Equivalences
	 * @description Retrieve all equivalence relationships in a project
	 */
	listEquivalences: {
		parameters: {
			query?: {
				/** @description Filter by equivalence status */
				status?: "suggested" | "confirmed" | "rejected";
				/** @description Number of items to skip */
				skip?: number;
				/** @description Maximum number of items to return */
				limit?: number;
			};
			path: {
				/** @description Unique identifier for the project */
				projectId: string;
			};
		};
		responses: {
			/** @description Successfully retrieved equivalences */
			200: {
				content: {
					"application/json": components["schemas"]["EquivalenceListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Detect Equivalences
	 * @description Automatically detect potential equivalent items across different views and dimensions
	 */
	detectEquivalences: {
		parameters: {
			path: {
				/** @description Unique identifier for the project */
				projectId: string;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["DetectEquivalencesRequest"];
			};
		};
		responses: {
			/** @description Equivalence detection completed successfully */
			200: {
				content: {
					"application/json": components["schemas"]["EquivalenceDetectionResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Confirm Equivalence
	 * @description Confirm a suggested equivalence relationship between items
	 */
	confirmEquivalence: {
		parameters: {
			path: {
				/** @description Unique identifier for the equivalence */
				id: string;
			};
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["ConfirmEquivalenceRequest"];
			};
		};
		responses: {
			/** @description Equivalence confirmed successfully */
			200: {
				content: {
					"application/json": components["schemas"]["EquivalenceResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Reject Equivalence
	 * @description Reject a suggested equivalence relationship between items
	 */
	rejectEquivalence: {
		parameters: {
			path: {
				/** @description Unique identifier for the equivalence */
				id: string;
			};
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["RejectEquivalenceRequest"];
			};
		};
		responses: {
			/** @description Equivalence rejected successfully */
			200: {
				content: {
					"application/json": components["schemas"]["EquivalenceResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * List Canonical Concepts
	 * @description Retrieve all canonical concepts in a project
	 */
	listCanonicalConcepts: {
		parameters: {
			query?: {
				/** @description Number of items to skip */
				skip?: number;
				/** @description Maximum number of items to return */
				limit?: number;
			};
			path: {
				/** @description Unique identifier for the project */
				projectId: string;
			};
		};
		responses: {
			/** @description Successfully retrieved canonical concepts */
			200: {
				content: {
					"application/json": components["schemas"]["CanonicalConceptListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Create Canonical Concept
	 * @description Create a new canonical concept from equivalent items
	 */
	createCanonicalConcept: {
		parameters: {
			path: {
				/** @description Unique identifier for the project */
				projectId: string;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateCanonicalConceptRequest"];
			};
		};
		responses: {
			/** @description Canonical concept created successfully */
			201: {
				content: {
					"application/json": components["schemas"]["CanonicalConceptResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Get Canonical Concept
	 * @description Retrieve detailed information about a specific canonical concept
	 */
	getCanonicalConcept: {
		parameters: {
			path: {
				/** @description Unique identifier for the canonical concept */
				id: string;
			};
		};
		responses: {
			/** @description Successfully retrieved canonical concept */
			200: {
				content: {
					"application/json": components["schemas"]["CanonicalConceptResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Get Concept Projections
	 * @description Retrieve all projections of a canonical concept across different dimensions
	 */
	getConceptProjections: {
		parameters: {
			query?: {
				/** @description Filter projections by specific dimension */
				dimension?: string;
			};
			path: {
				/** @description Unique identifier for the canonical concept */
				id: string;
			};
		};
		responses: {
			/** @description Successfully retrieved projections */
			200: {
				content: {
					"application/json": components["schemas"]["ProjectionListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Pivot Item to Canonical Concept
	 * @description Convert an item to a canonical concept projection, updating cross-dimensional references
	 */
	pivotItemToCanonical: {
		parameters: {
			path: {
				/** @description Unique identifier for the item to pivot */
				id: string;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PivotItemRequest"];
			};
		};
		responses: {
			/** @description Item pivoted successfully */
			200: {
				content: {
					"application/json": components["schemas"]["PivotItemResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * List Journeys
	 * @description Retrieve all journeys in a project
	 */
	listJourneys: {
		parameters: {
			query?: {
				/** @description Filter by journey type */
				type?: "user" | "system" | "data" | "integration";
				/** @description Number of items to skip */
				skip?: number;
				/** @description Maximum number of items to return */
				limit?: number;
			};
			path: {
				/** @description Unique identifier for the project */
				projectId: string;
			};
		};
		responses: {
			/** @description Successfully retrieved journeys */
			200: {
				content: {
					"application/json": components["schemas"]["JourneyListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Create Journey
	 * @description Create a new journey mapping requirements through a process
	 */
	createJourney: {
		parameters: {
			path: {
				/** @description Unique identifier for the project */
				projectId: string;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateJourneyRequest"];
			};
		};
		responses: {
			/** @description Journey created successfully */
			201: {
				content: {
					"application/json": components["schemas"]["JourneyResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Detect Journeys
	 * @description Automatically detect potential journeys from requirement traces
	 */
	detectJourneys: {
		parameters: {
			path: {
				/** @description Unique identifier for the project */
				projectId: string;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["DetectJourneysRequest"];
			};
		};
		responses: {
			/** @description Journey detection completed successfully */
			200: {
				content: {
					"application/json": components["schemas"]["JourneyDetectionResponse"];
				};
			};
			400: components["responses"]["BadRequest"];
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Get Journey
	 * @description Retrieve detailed information about a specific journey
	 */
	getJourney: {
		parameters: {
			path: {
				/** @description Unique identifier for the journey */
				id: string;
			};
		};
		responses: {
			/** @description Successfully retrieved journey */
			200: {
				content: {
					"application/json": components["schemas"]["JourneyResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * List Component Libraries
	 * @description Retrieve all component libraries in a project
	 */
	listComponentLibraries: {
		parameters: {
			query?: {
				/** @description Number of items to skip */
				skip?: number;
				/** @description Maximum number of items to return */
				limit?: number;
			};
			path: {
				/** @description Unique identifier for the project */
				projectId: string;
			};
		};
		responses: {
			/** @description Successfully retrieved component libraries */
			200: {
				content: {
					"application/json": components["schemas"]["ComponentLibraryListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * List Components in Library
	 * @description Retrieve all components in a specific library
	 */
	listLibraryComponents: {
		parameters: {
			query?: {
				/** @description Filter by component category */
				category?: string;
				/** @description Number of items to skip */
				skip?: number;
				/** @description Maximum number of items to return */
				limit?: number;
			};
			path: {
				/** @description Unique identifier for the component library */
				id: string;
			};
		};
		responses: {
			/** @description Successfully retrieved components */
			200: {
				content: {
					"application/json": components["schemas"]["ComponentListResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Get Component Usage
	 * @description Retrieve usage information for a specific component
	 */
	getComponentUsage: {
		parameters: {
			path: {
				/** @description Unique identifier for the component */
				id: string;
			};
		};
		responses: {
			/** @description Successfully retrieved component usage */
			200: {
				content: {
					"application/json": components["schemas"]["ComponentUsageResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	/**
	 * Get Design Tokens
	 * @description Retrieve design tokens for a component library
	 */
	getDesignTokens: {
		parameters: {
			query?: {
				/** @description Filter tokens by category (colors, typography, spacing, etc.) */
				category?: string;
			};
			path: {
				/** @description Unique identifier for the component library */
				id: string;
			};
		};
		responses: {
			/** @description Successfully retrieved design tokens */
			200: {
				content: {
					"application/json": components["schemas"]["DesignTokenResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
}
