apiVersion: 1

datasources:
  - name: Shared Traces
    type: tempo
    access: proxy
    url: ${PHENO_OBSERVABILITY_TEMPO_URL}
    uid: shared-traces
    editable: true
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
