"""Test constants for phase_five tests."""

# Count constants for bulk operations
COUNT_TWO = 2
COUNT_THREE = 3
COUNT_FOUR = 4
COUNT_FIVE = 5
COUNT_SIX = 6
COUNT_TEN = 10

# HTTP status codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_NO_CONTENT = 204
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_TOO_MANY_REQUESTS = 429
