"""Design Patterns for Pheno SDK.

This package contains implementations of common design patterns following hexagonal
architecture principles.
"""

from .creational import (
    ConfigurationFactory,
    DeploymentFactory,
    EntityFactory,
    RepositoryFactory,
    ServiceFactory,
    UseCaseFactory,
    UserFactory,
)
from .crud import (  # Base use cases; Decorators; Scaffolds; Mappers; Validators
    BaseActionUseCase,
    BaseCreateUseCase,
    BaseCRUDUseCase,
    BaseDeleteUseCase,
    BaseGetUseCase,
    BaseListUseCase,
    BaseUpdateUseCase,
    BaseUseCase,
    BusinessRuleValidator,
    CompositeMapper,
    CompositeValidator,
    CRUDScaffold,
    DTOMapper,
    DTOValidator,
    EntityMapper,
    EventMapper,
    FieldValidator,
    RepositoryScaffold,
    RouteScaffold,
    UseCaseScaffold,
    ValidationErrorHandler,
    crud_route,
    handle_errors,
    publish_events,
    use_case,
    validate_dto,
)
from .refactoring import (
    AnalysisResult,
    ArchitecturalViolation,
    ClassExtractor,
    CodeAnalyzer,
    CodeMetrics,
    ComplexityAnalyzer,
    ConcernExtractor,
    DependencyValidator,
    ExtractionResult,
    LayerExtractor,
    LayerValidator,
    PatternExtractor,
    PortAdapterValidator,
    ValidationIssue,
    ValidationResult,
    ValidationRule,
    analyze_complexity,
    detect_large_files,
    detect_violations,
    validate_dependencies,
    validate_layers,
    validate_port_adapter,
)
from .structural import (
    CachingDecorator,
    LoggingDecorator,
    MetricsDecorator,
    RepositoryFacade,
    RetryDecorator,
)

__all__ = [
    "AnalysisResult",
    "ArchitecturalViolation",
    "BaseActionUseCase",
    "BaseCRUDUseCase",
    "BaseCreateUseCase",
    "BaseDeleteUseCase",
    "BaseGetUseCase",
    "BaseListUseCase",
    "BaseUpdateUseCase",
    # CRUD patterns
    "BaseUseCase",
    "BusinessRuleValidator",
    "CRUDScaffold",
    # Structural patterns
    "CachingDecorator",
    "ClassExtractor",
    # Refactoring patterns
    "CodeAnalyzer",
    "CodeMetrics",
    "ComplexityAnalyzer",
    "CompositeMapper",
    "CompositeValidator",
    "ConcernExtractor",
    "ConfigurationFactory",
    "DTOMapper",
    "DTOValidator",
    "DependencyValidator",
    "DeploymentFactory",
    # Creational patterns
    "EntityFactory",
    "EntityMapper",
    "EventMapper",
    "ExtractionResult",
    "FieldValidator",
    "LayerExtractor",
    "LayerValidator",
    "LoggingDecorator",
    "MetricsDecorator",
    "PatternExtractor",
    "PortAdapterValidator",
    "RepositoryFacade",
    "RepositoryFactory",
    "RepositoryScaffold",
    "RetryDecorator",
    "RouteScaffold",
    "ServiceFactory",
    "UseCaseFactory",
    "UseCaseScaffold",
    "UserFactory",
    "ValidationErrorHandler",
    "ValidationIssue",
    "ValidationResult",
    "ValidationRule",
    "analyze_complexity",
    "crud_route",
    "detect_large_files",
    "detect_violations",
    "handle_errors",
    "publish_events",
    "use_case",
    "validate_dependencies",
    "validate_dto",
    "validate_layers",
    "validate_port_adapter",
]
