"""Parameterized MCP tools organized by domain."""

__all__ = [
    "project_manage",
    "item_manage",
    "link_manage",
    "trace_analyze",
    "graph_analyze",
    "specification_manage",
    "quality_analyze",
    "config_manage",
    "sync_manage",
    "export_manage",
    "import_manage",
    "ingestion_manage",
    "backup_manage",
    "file_watch_manage",
    "database_manage",
    "agent_manage",
    "progress_manage",
    "saved_query_manage",
    "test_manage",
    "tui_manage",
    "benchmark_manage",
    "chaos_manage",
    "design_manage",
]
