#!/usr/bin/env node
// ---------------------------------------------------------------------------
// generate.mjs — Reads tokens.ts and outputs CSS custom properties + JSON.
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ---------------------------------------------------------------------------
// Import the token definitions (they're plain JS exports).
// ---------------------------------------------------------------------------

const tokensPath = resolve(ROOT, 'tokens.ts');
let raw = readFileSync(tokensPath, 'utf-8');

// Strip TS type annotations so we can eval the file.
raw = raw
  .replace(/export const \w+ = /g, 'globalThis.__token__ = ')
  .replace(/as const;/g, ';');

// Evaluate the file to extract the token objects.
const moduleScope = {};
const fn = new Function('exports', 'require', 'module', '__filename', '__dirname', raw);
fn(moduleScope, () => {}, { exports: moduleScope }, tokensPath, ROOT);

const tokenNames = [
  'colors', 'typography', 'spacing', 'shadows',
  'borders', 'motion', 'breakpoints', 'zIndex',
];

// We actually need to re-parse from the source since the above is brittle.
// Instead, we'll import the object literals directly via a dynamic import workaround.
// For simplicity in this generator we'll re-read and eval all `export const` blocks.

const tokenVars = {};
for (const name of tokenNames) {
  const regex = new RegExp(`export const ${name}\\s*=\\s*(\\{[\\s\\S]*?\\});`);
  const match = raw.match(regex) || readFileSync(tokensPath, 'utf-8').match(regex);
  if (match) {
    // Convert the JS object literal to executable code.
    const objCode = `(${match[1]})`;
    tokenVars[name] = eval(objCode);
  }
}

// ---------------------------------------------------------------------------
// Flatten helpers
// ---------------------------------------------------------------------------

function flattenObject(obj, prefix = '', sep = '-') {
  const result = {};
  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}${sep}${key}` : key;
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      Object.assign(result, flattenObject(value, newKey, sep));
    } else {
      result[newKey] = value;
    }
  }
  return result;
}

// ---------------------------------------------------------------------------
// CSS custom properties
// ---------------------------------------------------------------------------

function generateCSS(tokens) {
  const lines = ['/* Auto-generated by generate.mjs — do not edit */'];
  lines.push(':root {');

  for (const name of tokenNames) {
    const tokenObj = tokens[name];
    if (!tokenObj) continue;
    lines.push(`  /* ${name} */`);
    const flat = flattenObject(tokenObj, name);
    for (const [key, value] of Object.entries(flat)) {
      lines.push(`  --${key}: ${value};`);
    }
    lines.push('');
  }

  lines.push('}');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// JSON output
// ---------------------------------------------------------------------------

function generateJSON(tokens) {
  const result = {};
  for (const name of tokenNames) {
    result[name] = tokens[name] ?? {};
  }
  return JSON.stringify(result, null, 2);
}

// ---------------------------------------------------------------------------
// Write outputs
// ---------------------------------------------------------------------------

const distDir = resolve(ROOT, 'dist');
mkdirSync(distDir, { recursive: true });

const css = generateCSS(tokenVars);
writeFileSync(resolve(distDir, 'tokens.css'), css, 'utf-8');
console.log(`✓ Wrote dist/tokens.css (${css.split('\n').length} lines)`);

const json = generateJSON(tokenVars);
writeFileSync(resolve(distDir, 'tokens.json'), json, 'utf-8');
console.log(`✓ Wrote dist/tokens.json (${json.split('\n').length} lines)`);

// Also write a minimal index.js that re-exports nothing (placeholder).
writeFileSync(
  resolve(distDir, 'index.js'),
  '// Auto-generated placeholder — tokens are consumed via CSS or JSON.\nmodule.exports = {};\n',
  'utf-8',
);
writeFileSync(
  resolve(distDir, 'index.d.ts'),
  '// Auto-generated placeholder.\nexport {};\n',
  'utf-8',
);
console.log('✓ Wrote dist/index.js and dist/index.d.ts');
