/**
 * Walks apps/web/src/lib/server/hono/routes/* and synthesizes a Hono AppType
 * export for sdk-js. Falls back to a stub if no routes exist yet.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import pc from 'picocolors';

const root = resolve(import.meta.dirname, '../../../');
const routesDir = resolve(root, 'apps/web/src/lib/server/hono/routes');
const out = resolve(root, 'packages/sdk-js/src/types.generated.ts');

if (!existsSync(routesDir)) {
  writeFileSync(out, '// generated by codegen-app-type; routes directory does not exist yet\n');
  console.log(pc.yellow('codegen: routes dir missing; emitted empty placeholder'));
  process.exit(0);
}

const files = readdirSync(routesDir).filter((f) => f.endsWith('.ts'));
const exports: string[] = [];
for (const f of files) {
  const text = readFileSync(resolve(routesDir, f), 'utf8');
  const name = f.replace(/\.ts$/u, '');
  exports.push(`  ${name}: { /* generated from ${f} */ },`);
}

const banner = '// AUTO-GENERATED by tools/scripts/src/codegen-app-type.ts — do not edit.\n';
const body = `export interface AppType {\n${exports.join('\n')}\n}\n`;
writeFileSync(out, banner + body);
console.log(pc.green(`codegen: wrote ${out} (${files.length} routes)`));
