#!/usr/bin/env python3
"""
Extract Coverage Metrics from CI Artifacts

This script parses coverage artifacts generated by CI/CD and produces
machine-readable output for baseline tracking and regression detection.

Usage:
    # Extract from local artifacts
    python scripts/extract_coverage_metrics.py --go backend/coverage.out \
                                               --python coverage.xml \
                                               --frontend frontend/apps/web/coverage-final.json \
                                               --output coverage-metrics.json

    # Extract from CI artifacts directory
    python scripts/extract_coverage_metrics.py --ci-artifacts-dir .artifacts/ \
                                               --output coverage-metrics.json

    # Generate baseline comparison
    python scripts/extract_coverage_metrics.py --compare coverage-baseline.json \
                                               --current coverage-metrics.json \
                                               --threshold 0.1
"""

import json
import sys
import argparse
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass, asdict
from datetime import datetime


@dataclass
class CoverageMetric:
    """Single coverage metric for a module/file"""
    name: str
    statements: float
    branches: float
    functions: float
    lines: float
    type: str  # "unit", "integration", "e2e"


@dataclass
class LanguageCoverage:
    """Aggregated coverage for a language"""
    language: str
    average: float
    total_files: int
    threshold: float
    status: str  # "✅", "⚠️", "❌"
    gap: float
    modules: List[CoverageMetric]


class CoverageExtractor:
    """Extract coverage metrics from various formats"""

    @staticmethod
    def parse_go_coverage(coverage_file: Path) -> Dict[str, float]:
        """
        Parse Go coverage.out file from go tool cover.

        Format: filename | coverage%
        """
        metrics = {}
        total = 0
        count = 0

        try:
            with open(coverage_file) as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("mode:"):
                        continue

                    parts = line.split()
                    if len(parts) >= 3:
                        filename = parts[0]
                        stmt_count = int(parts[1].split("/")[0])
                        stmt_total = int(parts[1].split("/")[1])

                        coverage = (stmt_count / stmt_total * 100) if stmt_total > 0 else 0
                        metrics[filename] = round(coverage, 2)
                        total += coverage
                        count += 1

        except Exception as e:
            print(f"Error parsing Go coverage: {e}", file=sys.stderr)
            return {}

        # Add average
        if count > 0:
            metrics["__average__"] = round(total / count, 2)
            metrics["__count__"] = count

        return metrics

    @staticmethod
    def parse_python_coverage(coverage_file: Path) -> Dict[str, float]:
        """
        Parse Python coverage.xml from pytest-cov.

        Extract per-package line coverage rates.
        """
        metrics = {}
        total = 0
        count = 0

        try:
            tree = ET.parse(coverage_file)
            root = tree.getroot()

            # Extract package-level coverage
            for package in root.findall(".//package"):
                name = package.get("name", "unknown")
                line_rate = float(package.get("line-rate", "0")) * 100

                metrics[name] = round(line_rate, 2)
                total += line_rate
                count += 1

        except Exception as e:
            print(f"Error parsing Python coverage: {e}", file=sys.stderr)
            return {}

        # Add average
        if count > 0:
            metrics["__average__"] = round(total / count, 2)
            metrics["__count__"] = count

        return metrics

    @staticmethod
    def parse_frontend_coverage(coverage_file: Path) -> Dict[str, float]:
        """
        Parse Frontend coverage-final.json from vitest coverage.

        Extract per-file coverage metrics.
        """
        metrics = {}
        total = 0
        count = 0

        try:
            with open(coverage_file) as f:
                data = json.load(f)

            # Iterate through file coverage
            for filepath, file_data in data.items():
                if isinstance(file_data, dict) and "lines" in file_data:
                    lines = file_data["lines"]

                    # Calculate line coverage
                    covered = sum(1 for line_data in lines.values() if line_data)
                    total_lines = len(lines)

                    coverage = (covered / total_lines * 100) if total_lines > 0 else 0
                    metrics[filepath] = round(coverage, 2)
                    total += coverage
                    count += 1

        except Exception as e:
            print(f"Error parsing Frontend coverage: {e}", file=sys.stderr)
            return {}

        # Add average
        if count > 0:
            metrics["__average__"] = round(total / count, 2)
            metrics["__count__"] = count

        return metrics

    @staticmethod
    def parse_pipe_delimited(filepath: Path) -> Dict[str, float]:
        """
        Parse pipe-delimited coverage format used by CI artifacts.

        Format: file|coverage%
        """
        metrics = {}
        total = 0
        count = 0

        try:
            with open(filepath) as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue

                    parts = line.split("|")
                    if len(parts) == 2:
                        name, cov_str = parts
                        try:
                            cov = float(cov_str)
                            metrics[name] = round(cov, 2)
                            total += cov
                            count += 1
                        except ValueError:
                            continue

        except Exception as e:
            print(f"Error parsing pipe-delimited file: {e}", file=sys.stderr)
            return {}

        # Add average
        if count > 0:
            metrics["__average__"] = round(total / count, 2)
            metrics["__count__"] = count

        return metrics


class CoverageAnalyzer:
    """Analyze coverage metrics"""

    THRESHOLDS = {
        "go": 90,
        "python": 90,
        "frontend": 90,
    }

    @staticmethod
    def calculate_status(coverage: float, threshold: float) -> Tuple[str, float]:
        """
        Calculate status and gap for coverage metric.

        Returns: (status_emoji, gap_percentage)
        """
        gap = coverage - threshold

        if coverage >= threshold:
            status = "✅"
        elif coverage >= threshold - 5:
            status = "⚠️"
        else:
            status = "❌"

        return status, round(gap, 2)

    @staticmethod
    def aggregate_metrics(
        language: str, metrics: Dict[str, float]
    ) -> LanguageCoverage:
        """Aggregate metrics into language-level summary"""

        average = metrics.get("__average__", 0)
        count = metrics.get("__count__", 0)
        threshold = CoverageAnalyzer.THRESHOLDS.get(language, 90)

        status, gap = CoverageAnalyzer.calculate_status(average, threshold)

        return LanguageCoverage(
            language=language,
            average=average,
            total_files=count,
            threshold=threshold,
            status=status,
            gap=gap,
            modules=[],
        )


class RegressionDetector:
    """Detect coverage regressions"""

    REGRESSION_THRESHOLD = 0.1  # 0.1% tolerance

    @staticmethod
    def detect(
        baseline: Dict[str, float], current: Dict[str, float]
    ) -> Dict[str, Dict[str, float]]:
        """
        Detect regressions between baseline and current coverage.

        Returns dict with keys: regressions, improvements, unchanged
        """
        results = {"regressions": {}, "improvements": {}, "unchanged": {}}

        # Compare all modules in current
        for module, current_cov in current.items():
            if module.startswith("__"):
                continue

            baseline_cov = baseline.get(module, None)

            if baseline_cov is None:
                results["improvements"][module] = {
                    "baseline": None,
                    "current": current_cov,
                    "delta": None,
                }
            else:
                delta = current_cov - baseline_cov

                if delta < -RegressionDetector.REGRESSION_THRESHOLD:
                    results["regressions"][module] = {
                        "baseline": baseline_cov,
                        "current": current_cov,
                        "delta": round(delta, 2),
                    }
                elif delta > RegressionDetector.REGRESSION_THRESHOLD:
                    results["improvements"][module] = {
                        "baseline": baseline_cov,
                        "current": current_cov,
                        "delta": round(delta, 2),
                    }
                else:
                    results["unchanged"][module] = {
                        "baseline": baseline_cov,
                        "current": current_cov,
                        "delta": round(delta, 2),
                    }

        return results

    @staticmethod
    def format_report(results: Dict) -> str:
        """Format regression detection results as markdown"""
        report = []

        if results.get("regressions"):
            report.append("## ❌ Regressions Detected\n")
            report.append("| Module | Baseline | Current | Delta |")
            report.append("|--------|----------|---------|-------|")

            for module, data in results["regressions"].items():
                delta = data["delta"]
                report.append(
                    f"| {module} | {data['baseline']}% | {data['current']}% | {delta:+.2f}% |"
                )

            report.append("")

        if results.get("improvements"):
            report.append("## ✅ Improvements Detected\n")
            report.append("| Module | Baseline | Current | Delta |")
            report.append("|--------|----------|---------|-------|")

            for module, data in results["improvements"].items():
                delta = data.get("delta", "N/A")
                baseline = data["baseline"] or "N/A"
                report.append(
                    f"| {module} | {baseline} | {data['current']}% | {delta if isinstance(delta, str) else f'{delta:+.2f}%'} |"
                )

            report.append("")

        if not results.get("regressions"):
            report.append("## ✅ No Regressions Detected\n")
            report.append(f"Threshold: -{RegressionDetector.REGRESSION_THRESHOLD}%\n")

        return "\n".join(report)


def main():
    parser = argparse.ArgumentParser(
        description="Extract and analyze coverage metrics from CI artifacts"
    )

    # Input options
    parser.add_argument("--go", type=Path, help="Path to Go coverage.out file")
    parser.add_argument("--python", type=Path, help="Path to Python coverage.xml file")
    parser.add_argument("--frontend", type=Path, help="Path to Frontend coverage JSON")
    parser.add_argument(
        "--ci-artifacts-dir", type=Path, help="Directory with CI artifacts"
    )

    # Analysis options
    parser.add_argument(
        "--compare",
        type=Path,
        help="Baseline coverage JSON for regression detection",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.1,
        help="Regression threshold percentage (default: 0.1)",
    )

    # Output options
    parser.add_argument(
        "--output", type=Path, default=Path("coverage-metrics.json"), help="Output file"
    )
    parser.add_argument(
        "--format",
        choices=["json", "markdown", "csv"],
        default="json",
        help="Output format",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")

    args = parser.parse_args()

    # Collect metrics
    metrics = {}
    extractor = CoverageExtractor()

    # Parse CI artifacts directory if provided
    if args.ci_artifacts_dir:
        ci_dir = args.ci_artifacts_dir
        if (ci_dir / "go-coverage-by-file.txt").exists():
            metrics["go"] = extractor.parse_pipe_delimited(
                ci_dir / "go-coverage-by-file.txt"
            )
        if (ci_dir / "python-coverage-by-package.txt").exists():
            metrics["python"] = extractor.parse_pipe_delimited(
                ci_dir / "python-coverage-by-package.txt"
            )
        if (ci_dir / "frontend-coverage-by-file.txt").exists():
            metrics["frontend"] = extractor.parse_pipe_delimited(
                ci_dir / "frontend-coverage-by-file.txt"
            )

    # Parse individual files
    if args.go:
        metrics["go"] = extractor.parse_go_coverage(args.go)
    if args.python:
        metrics["python"] = extractor.parse_python_coverage(args.python)
    if args.frontend:
        metrics["frontend"] = extractor.parse_frontend_coverage(args.frontend)

    if not metrics:
        print("Error: No coverage files found", file=sys.stderr)
        return 1

    # Analyze metrics
    analyzer = CoverageAnalyzer()
    summary = {}

    for language, mets in metrics.items():
        if mets:
            summary[language] = analyzer.aggregate_metrics(language, mets)

    # Output results
    if args.format == "json":
        output_data = {
            "timestamp": datetime.utcnow().isoformat(),
            "metrics": metrics,
            "summary": {lang: asdict(cov) for lang, cov in summary.items()},
        }

        if args.compare:
            try:
                with open(args.compare) as f:
                    baseline = json.load(f).get("metrics", {})

                regressions = {}
                for language, current in metrics.items():
                    baseline_data = baseline.get(language, {})
                    detector = RegressionDetector()
                    regressions[language] = detector.detect(baseline_data, current)

                output_data["regressions"] = regressions

            except Exception as e:
                print(f"Warning: Could not compare with baseline: {e}", file=sys.stderr)

        with open(args.output, "w") as f:
            json.dump(output_data, f, indent=2)

        print(f"✅ Coverage metrics written to {args.output}")

    elif args.format == "markdown":
        report = ["# Coverage Analysis Report\n"]
        report.append(f"**Generated:** {datetime.utcnow().isoformat()}\n")

        for language, cov in summary.items():
            report.append(f"\n## {language.upper()}\n")
            report.append(f"- Average: {cov.average}%")
            report.append(f"- Threshold: {cov.threshold}%")
            report.append(f"- Gap: {cov.gap:+.2f}%")
            report.append(f"- Status: {cov.status}")
            report.append(f"- Files: {cov.total_files}\n")

        with open(args.output, "w") as f:
            f.write("\n".join(report))

        print(f"✅ Markdown report written to {args.output}")

    if args.verbose:
        print("\nCoverage Summary:")
        for language, cov in summary.items():
            print(f"  {language}: {cov.average}% ({cov.status})")

    return 0


if __name__ == "__main__":
    sys.exit(main())
