"""Pydantic schemas for TraceRTM."""

from tracertm.schemas.event import EventCreate, EventResponse
from tracertm.schemas.item import ItemCreate, ItemResponse, ItemUpdate
from tracertm.schemas.link import LinkCreate, LinkResponse
from tracertm.schemas.problem import (
    ProblemCreate,
    ProblemUpdate,
    ProblemResponse,
    ProblemListResponse,
    ProblemStatusTransition,
    ProblemClosure,
    RCARequest,
    FiveWhysAnalysis,
    FishboneAnalysis,
    WorkaroundUpdate,
    PermanentFixUpdate,
    ProblemActivityResponse,
)
from tracertm.schemas.process import (
    ProcessCreate,
    ProcessUpdate,
    ProcessResponse,
    ProcessListResponse,
    ProcessVersionCreate,
    ProcessActivation,
    ProcessDeprecation,
    ProcessExecutionCreate,
    ProcessExecutionUpdate,
    ProcessExecutionComplete,
    ProcessExecutionResponse,
)
from tracertm.schemas.test_case import (
    TestCaseCreate,
    TestCaseUpdate,
    TestCaseResponse,
    TestCaseListResponse,
    TestCaseStatusTransition,
    TestCaseReview,
    TestCaseDeprecation,
    TestCaseActivityResponse,
    TestCaseStats,
    TestStep,
)
from tracertm.schemas.test_suite import (
    TestSuiteCreate,
    TestSuiteUpdate,
    TestSuiteResponse,
    TestSuiteListResponse,
    TestSuiteStatusTransition,
    TestSuiteActivityResponse,
    TestSuiteActivitiesResponse,
    TestSuiteStats,
    TestSuiteTestCaseCreate,
    TestSuiteTestCaseResponse,
)
from tracertm.schemas.test_run import (
    TestRunCreate,
    TestRunUpdate,
    TestRunResponse,
    TestRunListResponse,
    TestRunStart,
    TestRunComplete,
    TestResultCreate,
    TestResultResponse,
    BulkTestResultsSubmit,
    TestRunActivityResponse,
    TestRunActivitiesResponse,
    TestRunStats,
)
from tracertm.schemas.test_coverage import (
    TestCoverageCreate,
    TestCoverageUpdate,
    TestCoverageResponse,
    TestCoverageListResponse,
    TestCoverageVerify,
    CoverageActivityResponse,
    TraceabilityMatrixItem,
    TraceabilityMatrixResponse,
    CoverageGapItem,
    CoverageGapsResponse,
    TestCaseCoverageSummary,
    CoverageStats,
)
from tracertm.schemas.webhook import (
    WebhookCreate,
    WebhookUpdate,
    WebhookResponse,
    WebhookListResponse,
    WebhookStatusUpdate,
    WebhookLogResponse,
    WebhookLogsResponse,
    WebhookStats,
    InboundWebhookPayload,
    InboundWebhookResponse,
)
from tracertm.schemas.account import (
    AccountCreate,
    AccountUpdate,
    AccountResponse,
    AccountUserResponse,
    AccountListResponse,
)
from tracertm.schemas.auth import (
    SignupRequest,
    LoginRequest,
    AuthResponse,
    UserResponse,
    AccountSwitchRequest,
)
from tracertm.schemas.specification import (
    # ADR Enums & Schemas
    ADRStatus,
    ADROption,
    ADRCreate,
    ADRUpdate,
    ADRResponse,
    ADRListResponse,
    ADRActivityResponse,
    ADRActivityListResponse,
    # Contract Enums & Schemas
    ContractStatus,
    ContractType,
    ContractCondition,
    StateTransition,
    ContractCreate,
    ContractUpdate,
    ContractResponse,
    ContractListResponse,
    ContractActivityResponse,
    ContractActivityListResponse,
    # Feature & Scenario Enums & Schemas
    FeatureStatus,
    ScenarioStatus,
    BDDStep,
    ScenarioExample,
    FeatureCreate,
    FeatureUpdate,
    FeatureResponse,
    FeatureListResponse,
    FeatureActivityResponse,
    FeatureActivityListResponse,
    ScenarioCreate,
    ScenarioUpdate,
    ScenarioResponse,
    ScenarioListResponse,
    ScenarioActivityResponse,
    ScenarioActivityListResponse,
    # Step Definition Enums & Schemas
    StepDefinitionType,
    StepDefinitionLanguage,
    StepDefinitionImplementation,
    StepDefinitionCreate,
    StepDefinitionUpdate,
    StepDefinitionResponse,
    StepDefinitionListResponse,
    # Requirement Quality Schemas
    RequirementQualityRead,
)
from tracertm.schemas.item_spec import (
    # Item Spec Enums
    RequirementType,
    ConstraintType,
    QualityDimension,
    TestType,
    TestResultStatus,
    VerificationStatus,
    RiskLevel,
    # Nested types
    QualityIssue,
    ChangeHistoryEntry,
    VerificationEvidence,
    Invariant,
    TestRunSummary,
    AcceptanceCriterion,
    SubtaskEntry,
    TimeEntry,
    BlockerEntry,
    ChecklistItem,
    ImpactAssessment,
    SemanticSimilarity,
    # Requirement Spec Schemas
    RequirementSpecCreate,
    RequirementSpecUpdate,
    RequirementSpecResponse,
    RequirementSpecListResponse,
    # Test Spec Schemas
    TestSpecCreate,
    TestSpecUpdate,
    TestSpecResponse,
    TestSpecListResponse,
    # Epic Spec Schemas
    EpicSpecCreate,
    EpicSpecUpdate,
    EpicSpecResponse,
    EpicSpecListResponse,
    # User Story Spec Schemas
    UserStorySpecCreate,
    UserStorySpecUpdate,
    UserStorySpecResponse,
    UserStorySpecListResponse,
    # Task Spec Schemas
    TaskSpecCreate,
    TaskSpecUpdate,
    TaskSpecResponse,
    TaskSpecListResponse,
    # Defect Spec Schemas
    DefectSpecCreate,
    DefectSpecUpdate,
    DefectSpecResponse,
    DefectSpecListResponse,
    # Statistics Schemas
    RequirementQualityStats,
    TestHealthStats,
    EpicProgressStats,
    UserStoryHealthStats,
    TaskProgressStats,
    DefectHealthStats,
    ItemSpecStats,
    # Bulk Operation Schemas
    ItemSpecBulkCreateRequest,
    ItemSpecBulkUpdateRequest,
    ItemSpecBulkOperationResponse,
)
from tracertm.schemas.execution import (
    ExecutionCreate,
    ExecutionUpdate,
    ExecutionResponse,
    ExecutionListResponse,
    ExecutionStart,
    ExecutionComplete,
    ExecutionArtifactCreate,
    ExecutionArtifactResponse,
    ExecutionArtifactListResponse,
    CodexAgentTaskCreate,
    CodexAgentTaskResponse,
    CodexAgentTaskListResponse,
    ExecutionEnvironmentConfigCreate,
    ExecutionEnvironmentConfigUpdate,
    ExecutionEnvironmentConfigResponse,
    VHSTapeGenerateRequest,
    VHSTapeResponse,
    ExecutionStats,
)
from tracertm.schemas.integration import (
    IntegrationProvider,
    CredentialType,
    CredentialStatus,
    MappingDirection,
    MappingStatus,
    ConflictResolutionStrategy,
    SyncEventType,
    SyncDirection,
    SyncQueueStatus,
    ConflictResolutionStatus,
    OAuthStartRequest,
    OAuthStartResponse,
    OAuthCallbackRequest,
    IntegrationCredentialCreate,
    IntegrationCredentialUpdate,
    IntegrationCredentialResponse,
    IntegrationCredentialList,
    CredentialValidationResult,
    IntegrationMappingCreate,
    IntegrationMappingUpdate,
    IntegrationMappingResponse,
    IntegrationMappingList,
    SyncQueueItemResponse,
    SyncQueueList,
    TriggerSyncRequest,
    TriggerSyncResponse,
    SyncStatusSummary,
    SyncStatusResponse,
    SyncLogResponse,
    SyncLogList,
    SyncConflictResponse,
    SyncConflictList,
    ConflictResolutionRequest,
    ConflictResolutionResponse,
    ExternalItemSearchRequest,
    ExternalItemSearchResponse,
    GitHubRepo,
    GitHubRepoList,
    GitHubIssue,
    GitHubPullRequest,
    LinearIssue,
    LinearTeam,
    LinearTeamList,
    IntegrationStats,
)

__all__ = [
    "EventCreate",
    "EventResponse",
    "ItemCreate",
    "ItemResponse",
    "ItemUpdate",
    "LinkCreate",
    "LinkResponse",
    # Problem schemas
    "ProblemCreate",
    "ProblemUpdate",
    "ProblemResponse",
    "ProblemListResponse",
    "ProblemStatusTransition",
    "ProblemClosure",
    "RCARequest",
    "FiveWhysAnalysis",
    "FishboneAnalysis",
    "WorkaroundUpdate",
    "PermanentFixUpdate",
    "ProblemActivityResponse",
    # Process schemas
    "ProcessCreate",
    "ProcessUpdate",
    "ProcessResponse",
    "ProcessListResponse",
    "ProcessVersionCreate",
    "ProcessActivation",
    "ProcessDeprecation",
    "ProcessExecutionCreate",
    "ProcessExecutionUpdate",
    "ProcessExecutionComplete",
    "ProcessExecutionResponse",
    # Test Case schemas
    "TestCaseCreate",
    "TestCaseUpdate",
    "TestCaseResponse",
    "TestCaseListResponse",
    "TestCaseStatusTransition",
    "TestCaseReview",
    "TestCaseDeprecation",
    "TestCaseActivityResponse",
    "TestCaseStats",
    "TestStep",
    # Test Suite schemas
    "TestSuiteCreate",
    "TestSuiteUpdate",
    "TestSuiteResponse",
    "TestSuiteListResponse",
    "TestSuiteStatusTransition",
    "TestSuiteActivityResponse",
    "TestSuiteActivitiesResponse",
    "TestSuiteStats",
    "TestSuiteTestCaseCreate",
    "TestSuiteTestCaseResponse",
    # Test Run schemas
    "TestRunCreate",
    "TestRunUpdate",
    "TestRunResponse",
    "TestRunListResponse",
    "TestRunStart",
    "TestRunComplete",
    "TestResultCreate",
    "TestResultResponse",
    "BulkTestResultsSubmit",
    "TestRunActivityResponse",
    "TestRunActivitiesResponse",
    "TestRunStats",
    # Test Coverage schemas
    "TestCoverageCreate",
    "TestCoverageUpdate",
    "TestCoverageResponse",
    "TestCoverageListResponse",
    "TestCoverageVerify",
    "CoverageActivityResponse",
    "TraceabilityMatrixItem",
    "TraceabilityMatrixResponse",
    "CoverageGapItem",
    "CoverageGapsResponse",
    "TestCaseCoverageSummary",
    "CoverageStats",
    # Webhook schemas
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookResponse",
    "WebhookListResponse",
    "WebhookStatusUpdate",
    "WebhookLogResponse",
    "WebhookLogsResponse",
    "WebhookStats",
    "InboundWebhookPayload",
    "InboundWebhookResponse",
    # Integration schemas
    "IntegrationProvider",
    "CredentialType",
    "CredentialStatus",
    "MappingDirection",
    "MappingStatus",
    "ConflictResolutionStrategy",
    "SyncEventType",
    "SyncDirection",
    "SyncQueueStatus",
    "ConflictResolutionStatus",
    "OAuthStartRequest",
    "OAuthStartResponse",
    "OAuthCallbackRequest",
    "IntegrationCredentialCreate",
    "IntegrationCredentialUpdate",
    "IntegrationCredentialResponse",
    "IntegrationCredentialList",
    "CredentialValidationResult",
    "IntegrationMappingCreate",
    "IntegrationMappingUpdate",
    "IntegrationMappingResponse",
    "IntegrationMappingList",
    "SyncQueueItemResponse",
    "SyncQueueList",
    "TriggerSyncRequest",
    "TriggerSyncResponse",
    "SyncStatusSummary",
    "SyncStatusResponse",
    "SyncLogResponse",
    "SyncLogList",
    "SyncConflictResponse",
    "SyncConflictList",
    "ConflictResolutionRequest",
    "ConflictResolutionResponse",
    "ExternalItemSearchRequest",
    "ExternalItemSearchResponse",
    "GitHubRepo",
    "GitHubRepoList",
    "GitHubIssue",
    "GitHubPullRequest",
    "LinearIssue",
    "LinearTeam",
    "LinearTeamList",
    "IntegrationStats",
    # Execution schemas
    "ExecutionCreate",
    "ExecutionUpdate",
    "ExecutionResponse",
    "ExecutionListResponse",
    "ExecutionStart",
    "ExecutionComplete",
    "ExecutionArtifactCreate",
    "ExecutionArtifactResponse",
    "ExecutionArtifactListResponse",
    "CodexAgentTaskCreate",
    "CodexAgentTaskResponse",
    "CodexAgentTaskListResponse",
    "ExecutionEnvironmentConfigCreate",
    "ExecutionEnvironmentConfigUpdate",
    "ExecutionEnvironmentConfigResponse",
    "VHSTapeGenerateRequest",
    "VHSTapeResponse",
    "ExecutionStats",
    # Account schemas
    "AccountCreate",
    "AccountUpdate",
    "AccountResponse",
    "AccountUserResponse",
    "AccountListResponse",
    # Auth schemas
    "SignupRequest",
    "LoginRequest",
    "AuthResponse",
    "UserResponse",
    "AccountSwitchRequest",
    # Specification schemas
    # ADR Enums & Schemas
    "ADRStatus",
    "ADROption",
    "ADRCreate",
    "ADRUpdate",
    "ADRResponse",
    "ADRListResponse",
    "ADRActivityResponse",
    "ADRActivityListResponse",
    # Contract Enums & Schemas
    "ContractStatus",
    "ContractType",
    "ContractCondition",
    "StateTransition",
    "ContractCreate",
    "ContractUpdate",
    "ContractResponse",
    "ContractListResponse",
    "ContractActivityResponse",
    "ContractActivityListResponse",
    # Feature & Scenario Enums & Schemas
    "FeatureStatus",
    "ScenarioStatus",
    "BDDStep",
    "ScenarioExample",
    "FeatureCreate",
    "FeatureUpdate",
    "FeatureResponse",
    "FeatureListResponse",
    "FeatureActivityResponse",
    "FeatureActivityListResponse",
    "ScenarioCreate",
    "ScenarioUpdate",
    "ScenarioResponse",
    "ScenarioListResponse",
    "ScenarioActivityResponse",
    "ScenarioActivityListResponse",
    # Step Definition Enums & Schemas
    "StepDefinitionType",
    "StepDefinitionLanguage",
    "StepDefinitionImplementation",
    "StepDefinitionCreate",
    "StepDefinitionUpdate",
    "StepDefinitionResponse",
    "StepDefinitionListResponse",
    # Requirement Quality Schemas
    "RequirementQualityRead",
    # Item Spec Enums
    "RequirementType",
    "ConstraintType",
    "QualityDimension",
    "TestType",
    "TestResultStatus",
    "VerificationStatus",
    "RiskLevel",
    # Item Spec Nested Types
    "QualityIssue",
    "ChangeHistoryEntry",
    "VerificationEvidence",
    "Invariant",
    "TestRunSummary",
    "AcceptanceCriterion",
    "SubtaskEntry",
    "TimeEntry",
    "BlockerEntry",
    "ChecklistItem",
    "ImpactAssessment",
    "SemanticSimilarity",
    # Requirement Spec Schemas
    "RequirementSpecCreate",
    "RequirementSpecUpdate",
    "RequirementSpecResponse",
    "RequirementSpecListResponse",
    # Test Spec Schemas
    "TestSpecCreate",
    "TestSpecUpdate",
    "TestSpecResponse",
    "TestSpecListResponse",
    # Epic Spec Schemas
    "EpicSpecCreate",
    "EpicSpecUpdate",
    "EpicSpecResponse",
    "EpicSpecListResponse",
    # User Story Spec Schemas
    "UserStorySpecCreate",
    "UserStorySpecUpdate",
    "UserStorySpecResponse",
    "UserStorySpecListResponse",
    # Task Spec Schemas
    "TaskSpecCreate",
    "TaskSpecUpdate",
    "TaskSpecResponse",
    "TaskSpecListResponse",
    # Defect Spec Schemas
    "DefectSpecCreate",
    "DefectSpecUpdate",
    "DefectSpecResponse",
    "DefectSpecListResponse",
    # Statistics Schemas
    "RequirementQualityStats",
    "TestHealthStats",
    "EpicProgressStats",
    "UserStoryHealthStats",
    "TaskProgressStats",
    "DefectHealthStats",
    "ItemSpecStats",
    # Bulk Operation Schemas
    "ItemSpecBulkCreateRequest",
    "ItemSpecBulkUpdateRequest",
    "ItemSpecBulkOperationResponse",
]
