name: Release Drafter
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  actions: read
  contents: read

jobs:
  release-drafter:
    timeout-minutes: 10
    uses: KooshaPari/phenoShared/.github/workflows/reusable/release-drafter.yml@d95bb6755390f73c56ea496b246d098fbf97bbe9
    permissions:
      contents: write
      pull-requests: write

